### ISSUE TITLE
Uplift plugin to work with CodeChecker 6.8

### ISSUE THREAD

**Issue by gyorb** [Ericsson/CodeCheckerEclipsePlugin#114]
- [x] cleanup code base  (no background CodeChecker server should be necessary)  #115
- [x] introduce proper plugin versioning (see #109)
- [x] use CodeChecker 6.8 to analyze the project and generate the plist report files #113
- [x] the generated plist files are parsed and processed by eclipse #116
- [x] Test the uplifted plugin with various Eclipse versions #117
- [x] Write/Extend the documentation for the refactored code.

**Comment by Vodorok** [comment]
A solution to versioning problem #109 was added in 5d5c10763af19214df5c1ecc2f44b374c1a39560.

**Comment by Vodorok** [comment]
Extended/updated documentation in f227dcd6361113f47edb28a30a36c78279809336.

**Comment by dkrupp** [comment]
tested with Eclipse 2018-09 and Oxygen-1
